missing proof on skylinks v1
SkynetLabs/skynet-webportal pull request #1074
Opened 2021-08-16 22:43 UTC by kwypchlo

in lua empty string evaluates to true, I request a minute of silence

2021-08-16 23:57 UTC, m-cat commented
@kwypchlo Under what conditions is the proof equal to `""`? I feel like the header should always be present, even if there is no proof in which case it should be set to `[]`.

2021-08-17 00:27 UTC, MSevey approved these changes

2021-08-17 09:17 UTC, kwypchlo commented
> @kwypchlo Under what conditions is the proof equal to `""`? I feel like the header should always be present, even if there is no proof in which case it should be set to `[]`.

It's not the header that equals to `""` but the nginx variable that I set with `set $skynet_proof '';` - nginx doesn't have null value and I had to initialise this variable with something. This variable only contains the proof if it gets it from skylink v2 /resolve endpoint. 

```lua
if isBase32v2 or isBase64v2 then
    local res = ngx.location.capture("/skynet/resolve/" .. ngx.var.skylink_v2)
    if res.status == ngx.HTTP_OK then
	    local json = require('cjson')
	    local resolve = json.decode(res.body)
	    ngx.var.skylink_v1 = resolve.skylink
	    ngx.var.skynet_proof = res.header["Skynet-Proof"]
    end
end
```

2021-08-17 17:21 UTC, m-cat reviewed
> This variable only contains the proof if it gets it from skylink v2 /resolve endpoint.

Just to confirm, this means the variable will always be set to `[]` for v1 links and not `""`?

I feel like the if-conditional is slightly redundant which is why I was confused. It can be `ngx.header["Skynet-Proof"] = ngx.var.skynet_proof ?? "[]"` or the equivalent in Lua (or whatever language that is), not a big deal though.

2021-08-17 17:25 UTC, m-cat commented
I can see the changes on `siasky.xyz` currently. In general it would be nice if PRs linked out to a deployed version so reviewers can verify the changes. Also, if they aren't already, PRs should be running a full test suite on the deployed version (e.g. the existing SDK integration tests) to catch regressions.

2021-08-17 17:29 UTC, m-cat requested changes
I still feel like the v1 case needs to be documented. It should at least say that the proof variable contains `[]` and not `""` (assuming that is the case).

2021-08-31 12:24 UTC, kwypchlo commented
I made some changes in the pull request and also included new skynet-requested-skylink response header in.

2021-08-31 13:29 UTC, MSevey approved these changes

2021-08-31 13:56 UTC, ro-tex approved these changes

2021-08-31 14:35 UTC, kwypchlo commented
not needed any more for now, already implemented in #1075

2021-08-31 14:35 UTC, closed without merging