Increase the request body size of the /skynet/restore endpoint to 5MB.
SkynetLabs/skynet-webportal pull request #1346
Opened 2021-11-03 08:58 UTC by ro-tex

# PULL REQUEST

## Overview

## Example for Visual Changes

## Checklist
Review and complete the checklist to ensure that the PR is complete before assigned to an approver.
 - [ ] All new methods or updated methods have clear docstrings
 - [ ] Testing added or updated for new methods
 - [ ] Verify if any changes impact the WebPortal Health Checks
 - [ ] Approriate documentation updated
 - [ ] Changelog file created

## Issues Closed

2021-11-03 10:35 UTC, kwypchlo requested changes
please make sure that this endpoint doesn't need authentication or add
```
include /etc/nginx/conf.d/include/sia-auth;
```

2021-11-03 10:35 UTC, kwypchlo commented on docker/nginx/conf.d/server/server.api
> +}
```suggestion
location /skynet/restore {
    include /etc/nginx/conf.d/include/cors;

    client_max_body_size 5M;
    proxy_set_header User-Agent: Sia-Agent;
    proxy_pass http://sia:9980;
}
```

2021-11-03 19:50 UTC, MSevey approved these changes

2021-11-08 15:31 UTC, kwypchlo approved these changes

2021-11-08 15:31 UTC, merged