ops(dashboard-v2): prepare Dockerfile
SkynetLabs/skynet-webportal pull request #1971
Opened 2022-04-05 13:33 UTC by meeh0w

## Overview

* Adds a Dockerfile for the new dashboard
* Fixes some stuff that came on the way (filename case-sensitivity, some wrong paths)

2022-04-05 13:49 UTC, MSevey submitted a review, later dismissed

2022-04-06 08:05 UTC, kwypchlo requested changes
Add your Dockerfile to linter list please

https://github.com/SkynetLabs/skynet-webportal/blob/master/.github/workflows/lint-dockerfiles.yml#L15-L22

2022-04-07 10:35 UTC, kwypchlo approved these changes

2022-04-07 10:59 UTC, peterjan approved these changes

2022-04-07 10:59 UTC, merged