Update portal control scripts
SkynetLabs/skynet-webportal pull request #1973
Opened 2022-04-06 10:00 UTC by ro-tex

# PULL REQUEST

## Overview

Update portal control scripts, so they can talk to the new health-check container.

## Example for Visual Changes

## Checklist
Review and complete the checklist to ensure that the PR is complete before assigned to an approver.
 - [ ] All new methods or updated methods have clear docstrings
 - [ ] Testing added or updated for new methods
 - [ ] Verify if any changes impact the WebPortal Health Checks
 - [ ] Approriate documentation updated
 - [ ] Changelog file created

## Issues Closed

2022-04-06 10:02 UTC, kwypchlo requested changes

2022-04-06 10:02 UTC, kwypchlo commented on scripts/portal-down.sh
> +reason=${reason:-"disabled manually"}
I think we shouldn't provide default reason, if none is provided cli will ask for a reason

2022-04-07 08:55 UTC, kwypchlo requested changes

2022-04-08 09:49 UTC, ro-tex commented on scripts/portal-down.sh
> +fi
yes but it's not clear how to give the reason. we don't have a list of "how to use" tips. so, scripts just error out on me without any guidance and I need to open them and read what's wrong while I'm in a hurry to solve another problem. this is not a great experience. that's why I added a little hint which is going to save me some time when I forget how to pass a reason.

2022-04-08 09:56 UTC, kwypchlo commented on scripts/portal-down.sh
> +fi
what do you mean, the message exactly says what is wrong :)

```
user@dev1:~$ docker exec health-check cli disable
cli disable <reason>

Mark portal as disabled (provide meaningful reason)

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Not enough non-option arguments: got 0, need at least 1
```

2022-04-08 09:59 UTC, kwypchlo approved these changes

2022-04-11 16:09 UTC, merged